- name: Update
  hosts: "*"
  remote_user: root

  tasks:
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
